[mongodb]
mongodb-dev.swarupmacha.online

[catalogue]
catalogue-dev.swarupmacha.online

[frontend]

[redis]
redis-dev.swarupmacha.online

[user]
user-dev.swarupmacha.online

[cart]
cart-dev.swarupmacha.online

[mysql]
mysql-dev.swarupmacha.online

[shipping]
shipping-dev.swarupmacha.online

[rabbitmq]
rabbitmq-dev.swarupmacha.online

[payment]
payment-dev.swarupmacha.online



[all:vars]
ansible_username=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.swarupmacha.online


