[mongodb]
mongodb-dev.swarupmacha.online

[catalogue]
catalogue-dev.swarupmacha.online

[frontend]

[redis]
redis-dev.swarupmacha.online
    - user
    - cart
    - mysql
    - shipping
    - frontend
    - rabbitmq
    - payment



[all:vars]
ansible_username=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.swarupmacha.online


